import numpy as np
import json
import random

def create_stage2_labels():
    print("Step 1/4: Loading Global ID Mappings from Stage 1...")
    # Load the mappings generated by pre5.py
    with open('data/node_id_mappings.json', 'r') as f:
        mappings = json.load(f)
    
    user_map = mappings['user_map']
    product_map = mappings['product_map']
    
    print("Step 2/4: Loading Anomaly Flags from text files...")
    anomaly_global_ids = []
    
    # 1. Process Anomalous Users from the new text file
    with open('labelling_asin_5_core.txt', 'r') as f:
        anom_users = [line.strip() for line in f if line.strip()]
        
    for uid in anom_users:
        if uid in user_map: # Ensure user survived pre5.py filtering
            anomaly_global_ids.append(user_map[uid])
            
    # 2. Process Anomalous Products from the new text file
    with open('labelling_asin_meta.txt', 'r') as f:
        anom_prods = [line.strip() for line in f if line.strip()]
        
    for asin in anom_prods:
        if asin in product_map: # Ensure product survived pre5.py filtering
            anomaly_global_ids.append(product_map[asin])
            
    num_anomalies = len(anomaly_global_ids)
    print(f"Mapped {num_anomalies} anomalies to valid Global Graph IDs.")
    
    print("Step 3/4: Sampling Normal Nodes for Balanced BCE Loss...")
    # Create a pool of all valid global IDs (Users + Products)
    all_graph_ids = set(user_map.values()).union(set(product_map.values()))
    
    # Subtract known anomalies to get the "Normal" pool
    normal_pool = list(all_graph_ids - set(anomaly_global_ids))
    
    # Sample an equal amount of normal nodes to balance the semi-supervised dataset
    normal_samples = random.sample(normal_pool, num_anomalies)
    
    print("Step 4/4: Compiling and Saving labels.npy...")
    # Create Binary Labels (1 = Anomaly, 0 = Normal)
    labels_1 = np.ones(num_anomalies, dtype=np.int64)
    labels_0 = np.zeros(num_anomalies, dtype=np.int64)
    
    # Combine Indices and Labels
    indices = np.concatenate([anomaly_global_ids, normal_samples])
    labels = np.concatenate([labels_1, labels_0])
    
    # Stack into [L, 2] shape and shuffle so train/val splits are randomized
    labels_final = np.column_stack((indices, labels))
    np.random.shuffle(labels_final)
    
    # Save for the Stage 2 GAT script
    np.save('labels.npy', labels_final)
    print(f"Success! Saved labels.npy with shape {labels_final.shape}")
    print(f" -> {num_anomalies} Anomalies (1)")
    print(f" -> {num_anomalies} Normal Samples (0)")

if __name__ == "__main__":
    # Ensure random seed is fixed for reproducible sampling
    random.seed(42)
    np.random.seed(42)
    create_stage2_labels()
